/* This file was generated by upb_generator from the input file:
 *
 *     xds/annotations/v3/security.proto
 *
 * Do not edit -- your changes will be discarded when the file is
 * regenerated.
 * NO CHECKED-IN PROTOBUF GENCODE */

#include <stddef.h>
#include "upb/generated_code_support.h"
#include "xds/annotations/v3/security.upb_minitable.h"
#include "xds/annotations/v3/status.upb_minitable.h"
#include "google/protobuf/descriptor.upb_minitable.h"

// Must be last.
#include "upb/port/def.inc"

typedef struct {
  upb_MiniTableField fields[2];
} xds__annotations__v3__FieldSecurityAnnotation_msg_init_Fields;

static const xds__annotations__v3__FieldSecurityAnnotation_msg_init_Fields xds_annotations_v3_FieldSecurityAnnotation__fields = {{
  {1, 8, 0, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
  {2, 9, 0, kUpb_NoSub, 8, (int)kUpb_FieldMode_Scalar | ((int)kUpb_FieldRep_1Byte << kUpb_FieldRep_Shift)},
}};

const upb_MiniTable xds__annotations__v3__FieldSecurityAnnotation_msg_init = {
  &xds_annotations_v3_FieldSecurityAnnotation__fields.fields[0],
  16, 2, kUpb_ExtMode_NonExtendable, 2, UPB_FASTTABLE_MASK(255), 0,
#ifdef UPB_TRACING_ENABLED
  "xds.annotations.v3.FieldSecurityAnnotation",
#endif
};

UPB_LINKARR_APPEND(upb_AllExts)
const upb_MiniTableExtension xds_annotations_v3_security_ext = {
  {99044135, 0, 0, UPB_SIZE(3, 4), 11, (int)kUpb_FieldMode_Scalar | (int)kUpb_LabelFlags_IsExtension | ((int)UPB_SIZE(kUpb_FieldRep_4Byte, kUpb_FieldRep_8Byte) << kUpb_FieldRep_Shift)},
  {.UPB_PRIVATE(submsg) = &xds__annotations__v3__FieldSecurityAnnotation_msg_init},
  &google__protobuf__FieldOptions_msg_init,

};
static const upb_MiniTable *messages_layout[1] = {
  &xds__annotations__v3__FieldSecurityAnnotation_msg_init,
};


static const upb_MiniTableExtension *extensions_layout[1] = {
  &xds_annotations_v3_security_ext,
};

const upb_MiniTableFile xds_annotations_v3_security_proto_upb_file_layout = {
  messages_layout,
  NULL,
  extensions_layout,
  1,
  0,
  1,
};

#include "upb/port/undef.inc"

