# Copyright 2026 The gRPC Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import base64
import itertools
import logging
import json
import re

_MIRROR_SITE_PATTERN = "https://storage.googleapis.com/grpc-bazel-mirror"
_SUPPORTED_RULE_KINDS = [
    "http_archive",
    "http_file",
    "python_repository",
    "whl_library",
]
_LOGGED_FIELDS = ["repoRuleName", "name", "canonicalName", "apparentName"]

_BAZEL_URLS = [
    "https://github.com/bazelbuild/bazel/releases/download/8.7.0/bazel-8.7.0-linux-arm64",
    "https://github.com/bazelbuild/bazel/releases/download/8.7.0/bazel-8.7.0-linux-x86_64",
    "https://github.com/bazelbuild/bazel/releases/download/8.7.0/bazel-8.7.0-darwin-x86_64",
    "https://github.com/bazelbuild/bazel/releases/download/8.7.0/bazel-8.7.0-windows-x86_64.exe",
]

logger = logging.getLogger(__name__)


def parse_ndjson(file_path):
    repos = []
    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            obj = json.loads(line)
            repos.append(obj)
    return repos


def parse_workspace_urls():
    url_pattern = re.compile(r'"(https://github.com/[^"]+)')
    with open("bazel/grpc_deps.bzl", "r", encoding="utf-8") as f:
        for line in f:
            match = re.search(url_pattern, line)
            if match:
                yield match.group(1)


def parse_cmake_urls():
    url_pattern = re.compile(r"\s*- (https://github.com/.+\.(tar\.gz|zip))")
    with open("build_autogenerated.yaml", "r", encoding="utf-8") as f:
        for line in f:
            match = re.search(url_pattern, line)
            if match:
                yield match.group(1)


def parse_bzlmod_urls(input_path):
    repos = parse_ndjson(input_path)
    for repo in repos:
        if repo["repoRuleName"] not in _SUPPORTED_RULE_KINDS:
            continue
        urls = []
        for attr in repo["attribute"]:
            if attr["name"] == "url" and attr["stringValue"]:
                urls.append(attr["stringValue"])
            elif attr["name"] == "urls":
                urls.extend(attr.get("stringListValue", list()))

        logging_data = {k: repo[k] for k in _LOGGED_FIELDS if k in repo}
        logging_data["urls"] = urls
        logger.debug(
            f"Processing repo definition: {json.dumps(logging_data, indent=4)}"
        )
        for url in urls:
            yield url


def parse_existing_archives(input_path):
    with open(input_path, "r", encoding="utf-8") as f:
        for line in f:
            yield line.strip()


def main():
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--bzlmod_deps_file",
        type=str,
        help="the ndjson file generated by `bazel mod show_repo`",
        required=True,
    )
    parser.add_argument(
        "--existing_archives_file",
        type=str,
        help="A file enlisting all mirrored archive files",
        required=True,
    )
    parser.add_argument(
        "--output_file",
        type=str,
        help="A output file where each line is an url we should mirror.",
        required=True,
    )
    args = parser.parse_args()
    urls = set(
        itertools.chain(
            _BAZEL_URLS,
            parse_cmake_urls(),
            parse_workspace_urls(),
            parse_bzlmod_urls(args.bzlmod_deps_file),
        )
    )
    existing_urls = set(
        parse_existing_archives(
            args.existing_archives_file,
        )
    )
    urls_to_upload = sorted(
        [url for url in urls - existing_urls if _MIRROR_SITE_PATTERN not in url]
    )
    output = "\n".join(urls_to_upload)
    with open(args.output_file, "w") as file:
        contents = file.write(output)


if __name__ == "__main__":
    main()
