# TODO: Move to test/distrib/python.

local_repository(
    name = "com_github_grpc_grpc",
    path = "../../../..",
)

# Ensure rules don't rely on __main__ naming convention.
workspace(name = "python_test_repo")

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")

grpc_extra_deps()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

local_repository(
    name = "some_other_repo",
    path = "../python_second_test_repo",
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python_3_11",
    python_version = "3.11",
)
